name: Run TMDB Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run TMDB script
      run: python extrair.py
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    - name: Add result file
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add -f resultados.txt
        git commit -m "Adiciona resultados.txt"
        git push
      continue-on-error: true

    - name: List files in the repository
      run: cat resultados.txt  # Exibe o conteúdo do arquivo resultados.txt
